### ISSUE TITLE
rewriter bad site data error handling

### ISSUE THREAD

**Issue by elv-todd** [eluv-io/elv-live#10]
**Description**

when we have misconfigured site data, we get this:

---
```
severity: "ERROR"
textPayload: "TypeError: Cannot read properties of undefined (reading 'event_info')
    at loadElvLiveAsync (/workspace/index.js:185:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /workspace/index.js:107:15"
timestamp: "2022-10-17T20:26:11.430304Z"
trace: "projects/elv-rewriter/traces/77526bc175a637383d94e9f4cff4ede9"
```

in our logs:
- https://console.cloud.google.com/logs/query;timeRange=PT15M;cursorTimestamp=2022-10-17T20:28:35.270617Z?authuser=0&project=elv-rewriter

**To Reproduce**

it's currently happening on main / staging, will capture the json and attach

we can test main/staging via a secondary firebase site deployment: 
- https://elv-rewriter.web.app/create_index_html

contrast with demov3 / staging, which is also supported; access via:
- https://elv-rewriter.firebaseapp.com/create_index_html

Notice that prod returns proper metadata, while staging returns only defaults (the error interrupts loading)

``` 
curl -s https://live.eluv.io/eluvio/community | grep "\(title\|link\)"
    <title>WEB3 FULL THROTTLE</title>

curl -s https://live-stg-eluv-io.web.app/eluvio/community | grep "\(title\|link\)"
    <title>Eluvio: The Content Blockchain</title>
```

**Fix**

this is done via the `tenant-index-metadata-rewriter-deployer` branch

**Comment by elv-todd** [comment]
Branch 'elv-live-issue-10-adapt-rewriter-to-bad-site-data'

**Comment by elv-todd** [comment]
issue is "eluvio-hackathon-eluvio-live-tenant" -- 

```
eluvio-hackathon-eluvio-live-tenant/site-eluvio-hackathon: {
site: "site-eluvio-hackathon"
tenant: "eluvio-hackathon-eluvio-live-tenant"
}
```
![broken-site](https://user-images.githubusercontent.com/108554594/196324702-d3c608f1-4976-42fb-94b2-546c9962a465.png)
